export const synopsisList = {
    leiden: {
        type: "direct_sources",
        code: "leiden", 
        name: "כתב יד ליידן",
        button_code: "leiden",
        shortName: "ל",
    },
    leiden_2: {
        type: "direct_sources",
        code: "leiden", 
        name: "כתב יד ליידן ב׳",
        button_code: "leiden_2",
        shortName: "ל2",
    },
    rome: {
        type: "direct_sources",
        code: "rome", 
        name: "כתב יד רומי",
        button_code: "rome",
        shortName: "ר",
    },
    escorial: {
        type: "direct_sources",
        code: "escorial",
        name: "כתב יד אסקוריאל",
        button_code: "escorial",
        shortName: "א",
    },
    munich: {
        type: "direct_sources",
        code: "munich",
        name: "כתב יד מינכן",
        button_code: "munich",
        shortName: "מ",
    },
    oxford: {
        type: "direct_sources",
        code: "oxford",
        name: "כתב יד אוקספורד",
        button_code: "oxford",
        shortName: "או",
    },
    dfus_rishon: {
        type: "direct_sources",
        code: "dfus_rishon", 
        name: "דפוס ראשון",
        button_code: "dfus_rishon",
        shortName: "ד",
    },
    gniza_1: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה א׳",
        button_code: "gniza_1",
        shortName: "ג1",
    },
    gniza_2: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה ב׳",
        button_code: "gniza_2",
        shortName: "ג2",
    },
    gniza_3: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה ג׳",
        button_code: "gniza_3",
        shortName: "ג3",
    },
    gniza_4: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה ד׳",
        button_code: "gniza_4",
        shortName: "ג4",
    },
    gniza_5: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה ה׳",
        button_code: "gniza_5",
        shortName: "ג5",
    },
    gniza_6: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה ו׳",
        button_code: "gniza_6",
        shortName: "ג6",
    },
    gniza_7: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה ז׳",
        button_code: "gniza_7",
        shortName: "ג7",
    },
    gniza_8: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה ח׳",
        button_code: "gniza_8",
        shortName: "ג8",
    },
    gniza_9: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה ט׳",
        button_code: "gniza_9",
        shortName: "ג9",
    },
    gniza_10: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה י׳",
        button_code: "gniza_10",
        shortName: "ג10",
    },
    gniza_11: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה יא׳",
        button_code: "gniza_11",
        shortName: "ג11",
    },
    kricha_1: {
        type: "direct_sources",
        code: "kricha", 
        button_code: "kricha_1",
        name: "קטע כריכה א׳",
        shortName: "כ1",
    },
    kricha_2: {
        type: "direct_sources",
        code: "kricha", 
        button_code: "kricha_2",
        name: "קטע כריכה ב׳",
        shortName: "כ2",
    },
    kricha_3: {
        type: "direct_sources",
        code: "kricha", 
        button_code: "kricha_3",
        name: "קטע כריכה ג׳",
        shortName: "כ3",
    },
    kricha_4: {
        type: "direct_sources",
        code: "kricha", 
        button_code: "kricha_4",
        name: "קטע כריכה ד׳",
        shortName: "כ4",
    },
    kricha_5: {
        type: "direct_sources",
        code: "kricha", 
        button_code: "kricha_5",
        name: "קטע כריכה ה׳",
        shortName: "כ5",
    },
    kricha_6: {
        type: "direct_sources",
        code: "kricha", 
        button_code: "kricha_5",
        name: "קטע כריכה ו׳",
        shortName: "כ6",
    },
    kricha_7: {
        type: "direct_sources",
        code: "kricha", 
        button_code: "kricha_7",
        name: "קטע כריכה ז׳",
        shortName: "כ7",
    },
    kricha_8: {
        type: "direct_sources",
        code: "kricha", 
        button_code: "kricha_8",
        name: "קטע כריכה ח׳",
        shortName: "כ8",
    },
    kricha_13: {
        type: "direct_sources",
        code: "kricha", 
        button_code: "kricha_13",
        name: "קטע כריכה יג׳",
        letter: "כ",
        shortName: "כ13",
    },
    kricha_14: {
        type: "direct_sources",
        code: "kricha", 
        button_code: "kricha_14",
        name: "קטע כריכה יד׳",
        letter: "יד",
        shortName: "כ14",
    },
    likutim_2: {
        type: "direct_sources",
        code: "likutim", 
        button_code: "likutim_2",
        name: "ליקוטים ב׳",
        shortName: "לק2",
    },
    likutim_3: {
        type: "direct_sources",
        code: "likutim", 
        button_code: "likutim_3",
        name: "ליקוטים ג׳",
        shortName: "לק3",
    },
    likutim_4: {
        type: "direct_sources",
        code: "likutim", 
        button_code: "likutim_4",
        name: "ליקוטים ד׳",
        shortName: "לק4",
    },
    likutim_5: {
        type: "direct_sources",
        code: "likutim", 
        button_code: "likutim_5",
        name: "ליקוטים ה׳",
        shortName: "לק5",
    },
    likutim_12: {
        type: "direct_sources",
        code: "likutim", 
        button_code: "likutim_12",
        name: "ליקוטים יב׳",
        shortName: "לק12",
    },
    likutim_l_1: {
        type: "direct_sources",
        code: "likutim", 
        button_code: "likutim_l_1",
        name: "ליקוטים ל׳ א׳",
        shortName: "לק-ל1",
    },
    likutim_l_2: {
        type: "direct_sources",
        code: "likutim", 
        button_code: "likutim_l_2",
        name: "ליקוטים ל׳ ב׳",
        shortName: "לק-ל2",
    },
    likutim_l_3: {
        type: "direct_sources",
        code: "likutim", 
        button_code: "likutim_l_3",
        name: "ליקוטים ל׳ ג׳",
        shortName: "לק-ל3",
    },
    translation: {
        type: "translation",
        code: "translation", 
        button_code: "translation",
        name: "תרגום",
        shortName: "תרגום",
    },

}
