export const synopsisList = {
    leiden: {
        type: "direct_sources",
        code: "leiden", 
        name: "כתב יד ליידן",
        button_code: "leiden",
    },
    rome: {
        type: "direct_sources",
        code: "rome", 
        name: "כתב יד רומי",
        button_code: "rome",
    },
    escorial: {
        type: "direct_sources",
        code: "escorial",
        name: "כתב יד אסקוריאל",
        button_code: "escorial",
    },
    munich: {
        type: "direct_sources",
        code: "munich",
        name: "כתב יד מינכן",
        button_code: "munich",
    },
    oxford: {
        type: "direct_sources",
        code: "oxford",
        name: "כתב יד אוקספורד",
        button_code: "oxford",
    },
    dfus_rishon: {
        type: "direct_sources",
        code: "dfus_rishon", 
        name: "דפוס ראשון",
        button_code: "dfus_rishon",
    },
    gniza_1: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה א׳",
        button_code: "gniza_1",
    },
    gniza_2: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה ב׳",
        button_code: "gniza_2",
    },
    gniza_3: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה ג׳",
        button_code: "gniza_3",
    },
    gniza_4: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה ד׳",
        button_code: "gniza_4",
    },
    gniza_5: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה ה׳",
        button_code: "gniza_5",
    },
    gniza_6: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה ו׳",
        button_code: "gniza_6",
    },
    gniza_7: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה ז׳",
        button_code: "gniza_7",
    },
    gniza_8: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה ח׳",
        button_code: "gniza_8",
    },
    gniza_9: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה ט׳",
        button_code: "gniza_9",
    },
    gniza_10: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה י׳",
        button_code: "gniza_10",
    },
    gniza_11: {
        type: "direct_sources",
        code: "gniza", 
        name: "גניזה יא׳",
        button_code: "gniza_11",
    },
    kricha_2: {
        type: "direct_sources",
        code: "kricha", 
        button_code: "kricha_2",
        name: "קטע כריכה ב׳",
    },
    kricha_3: {
        type: "direct_sources",
        code: "kricha", 
        button_code: "kricha_3",
        name: "קטע כריכה ג׳",
    },
    kricha_13: {
        type: "direct_sources",
        code: "kricha", 
        button_code: "kricha_13",
        name: "קטע כריכה יג׳",
        letter: "כ",
    },
    kricha_14: {
        type: "direct_sources",
        code: "kricha", 
        button_code: "kricha_14",
        name: "קטע כריכה יד׳",
        letter: "יד",
    },
    likutim_2: {
        type: "direct_sources",
        code: "likutim", 
        button_code: "likutim_2",
        name: "ליקוטים ב׳",
    },
    likutim_3: {
        type: "direct_sources",
        code: "likutim", 
        button_code: "likutim_3",
        name: "ליקוטים ג׳",
    },
    likutim_4: {
        type: "direct_sources",
        code: "likutim", 
        button_code: "likutim_4",
        name: "ליקוטים ד׳",
    },
    likutim_5: {
        type: "direct_sources",
        code: "likutim", 
        button_code: "likutim_5",
        name: "ליקוטים ה׳",
    },
    likutim_12: {
        type: "direct_sources",
        code: "likutim", 
        button_code: "likutim_12",
        name: "ליקוטים יב׳",
    },
    likutim_l_1: {
        type: "direct_sources",
        code: "likutim", 
        button_code: "likutim_l_1",
        name: "ליקוטים ל׳ א׳",
    },
    likutim_l_2: {
        type: "direct_sources",
        code: "likutim", 
        button_code: "likutim_l_2",
        name: "ליקוטים ל׳ ב׳",
    },
    likutim_l_3: {
        type: "direct_sources",
        code: "likutim", 
        button_code: "likutim_l_3",
        name: "ליקוטים ל׳ ג׳",
    },


}
